name: Monitor Parts Weights

on:
  workflow_dispatch:  # Only allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache state data
      uses: actions/cache@v3
      with:
        path: .data
        key: parts-state-${{ github.run_id }}
        restore-keys: |
          parts-state-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > service-account.json
      env:
        ACTIONS_STEP_DEBUG: false
    
    - name: Run monitoring script
      env:
        SPACE_WEBHOOK_URL: ${{ secrets.SPACE_WEBHOOK_URL }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        ACTIONS_STEP_DEBUG: false
      run: python monitor_parts.py 